version: "3.8"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  issue-tracker:
    build: ./IssueTracker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./IssueTracker:/IssueTracker
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env

  app:
    build: ./frontend
    command: yarn start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

volumes:
  pgdata:
