# Generated by Django 3.1.7 on 2021-06-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTrackerApp', '0004_auto_20210526_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default=''),
        ),
    ]
