# Generated by Django 3.1.7 on 2021-06-21 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTrackerApp', '0005_user_avatar_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-updated_at']},
        ),
    ]
